version: "2"

volumes:
  gems:
    driver: local
  postgres-data:
    driver: local

services:
  db: 
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret123
  web:
    image: ruby:2.3.0
    volumes:
      - .:/usr/src/my_app
      - gems:/usr/local/bundle
    working_dir: /usr/src/my_app
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:secret123@db:5432/my_app_development