version: "2"

volumes:
  gems:
    driver: local
  postgres-data:
    driver: local

services:
  db: 
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret123
  web:
    image: ruby:2.3.0
    command: rails server -b 0.0.0.0 -P /tmp/server.pid
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/my_app
      - gems:/usr/local/bundle
    working_dir: /usr/src/my_app
    tty: true
    stdin_open: true
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:secret123@db:5432/my_app_development
    env_file:
      - development.env